apiVersion: v1
kind: Service
metadata:
  name: LicensePlateRecognition
spec:
  selector:
    app: LicensePlateRecognition
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8003
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: LicensePlateRecognition
spec:
  selector:
    matchLabels:
      app: LicensePlateRecognition
  replicas: 1
  template:
    metadata:
      labels:
        app: riceleafdiseases
    spec:
      containers:
      - name: LicensePlateRecognition
        image: LicensePlateRecognition
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003